import { invoke } from '@tauri-apps/api/core'
import { useReferencesStore } from '../stores/references'

/**
 * Auto-generates a `references.bib` file from the reference library.
 * Called before each LaTeX compilation to ensure citations are up to date.
 *
 * @param {string} texPath - Path to the .tex file being compiled
 * @returns {string} Path to the generated .bib file
 */
export async function ensureBibFile(texPath) {
  const referencesStore = useReferencesStore()

  // Generate .bib in the same directory as the .tex file
  const dir = texPath.substring(0, texPath.lastIndexOf('/'))
  const bibPath = dir + '/references.bib'

  // Export all references as BibTeX
  const bibContent = referencesStore.exportBibTeX()

  if (!bibContent.trim()) {
    // No references — still write an empty file so \bibliography doesn't error
    await invoke('write_file', { path: bibPath, content: '% Auto-generated by Shoulders\n' })
    return bibPath
  }

  const header = '% Auto-generated by Shoulders from reference library\n% Do not edit manually — changes will be overwritten on next compile\n\n'
  await invoke('write_file', { path: bibPath, content: header + bibContent + '\n' })

  return bibPath
}
